#!/bin/zsh
cat <<EOF | ssh yagni -T
    cd /home/arctair/dash-serve.snare.cc
    git fetch
    git reset origin/main --hard
    systemctl daemon-reload --user
    systemctl restart dash-serve.snare.cc --user
EOF
